prometheus:
  prometheusSpec:
    resources:
      requests:
        memory: 128Mi
      limits:
        memory: 2048Mi
kubeControllerManager:
  enabled: true
kubeScheduler:
  enabled: true
coreDns:
  enabled: true
kubeDns:
  enabled: false
grafana:
  repository: grafana/grafana
  tag: 6.4.2
  adminPassword: 12tsh3
  env:
    GF_SERVER_DOMAIN: false
    GF_SERVER_ROOT_URL: http://localhost
    GF_AUTH_ANONYMOUS_ORG_NAME: local
    GF_USERS_ALLOW_SIGN_UP: false
  additionalDataSources:
  - name: Logs
    type: loki
    access: proxy
    url: http://loki.monitoring.svc.cluster.local:3100
    jsonData:
      maxLines: 1000
  grafana.ini:
    paths:
      data: /var/lib/grafana/data
      logs: /var/log/grafana
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning
    analytics:
      check_for_updates: true
    log:
      mode: console
    grafana_net:
      url: https://grafana.net
  extraEmptyDirMounts:
    - name: provisioning-notifiers
      mountPath: /etc/grafana/provisioning/notifiers
  notifiers:
    notifiers.yaml:
      notifiers:
      - name: prometheus-alertmanager-notifier
        type: prometheus-alertmanager
        uid: prometheus-alertmanager1
        org_id: 1
        is_default: true
        settings:
          url: http://prometheus-operator-alertmanager.monitoring.svc.cluster.local:9093
  sidecar:
    dashboards:
      searchNamespace: ALL
    datasources:
      searchNamespace: ALL
alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 24h
      receiver: 'null'
      routes:
      - match:
          alertname: Watchdog
        receiver: 'null'
    receivers:
    - name: 'null'
    templates:
      - '/etc/alertmanager/config/notifications_slack.tmpl'
  templateFiles:
    notifications_slack.tmpl: |-
      {{ define "__single_message_title" }}{{ range .Alerts.Firing }}{{ .Labels.alertname }} @ {{ .Annotations.identifier }}{{ end }}{{ range .Alerts.Resolved }}{{ .Labels.alertname }} @ {{ .Annotations.identifier }}{{ end }}{{ end }}
      {{ define "custom_title" }}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ if or (and (eq (len .Alerts.Firing) 1) (eq (len .Alerts.Resolved) 0)) (and (eq (len .Alerts.Firing) 0) (eq (len .Alerts.Resolved) 1)) }}{{ template "__single_message_title" . }}{{ end }}{{ end }}
      {{ define "custom_slack_message" }}
      {{ if or (and (eq (len .Alerts.Firing) 1) (eq (len .Alerts.Resolved) 0)) (and (eq (len .Alerts.Firing) 0) (eq (len .Alerts.Resolved) 1)) }}
      {{ range .Alerts.Firing }}{{ .Annotations.message }}{{ end }}{{ range .Alerts.Resolved }}{{ .Annotations.message }}{{ end }}
      {{ else }}
      {{ if gt (len .Alerts.Firing) 0 }}
      *Alerts Firing:*
      {{ range .Alerts.Firing }}- {{ .Annotations.message }}
      {{ end }}{{ end }}
      {{ if gt (len .Alerts.Resolved) 0 }}
      *Alerts Resolved:*
      {{ range .Alerts.Resolved }}- {{ .Annotations.message }}
      {{ end }}{{ end }}
      {{ end }}
      {{ end }}
